hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "m.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 32
initial_increment: 20  
increment: ${initial_increment}
scenario: "class"
dataset: "cub200"
# add conig
num_workers: 16
train_batch_size: 32
epochs: 15
lr: 0.001
fp16: false
seed: 2
margin: 0.2
milestones: [4,10]
beta: 1
mix_bias: 0.8
threshold: 0.65
shrinkage: True

