hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 128
initial_increment: 50  
increment: 10
scenario: "class"
dataset: "imagenet100"
num_workers: 16
train_batch_size: 128
epochs: 15
lr: 0.001
fp16: false
seed: 2
milestones: [4,10]
beta: 1
mix_bias: 0.5
threshold: 0.65
shrinkage: False