hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metric.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 64
initial_increment: 100  
increment: 10
scenario: "class"
dataset: "imagenet_R"
num_workers: 16
train_batch_size: 64
epochs: 15
lr: 0.001
fp16: false
seed: 2
milestones: [4,10]
beta: 2 
mix_bias: 0.7
threshold: 0.65
shrinkage: True
